### ISSUE TITLE
Broken kerbal portrait view on several parts.

### ISSUE THREAD

**Issue by ra4nd0m** [post-kerbin-mining-corporation/StationPartsExpansionRedux#236]
It seems that camera in few modules is clipping into some textures. This happens on:
2.5 station core, places 1 and 2. 
![image](https://user-images.githubusercontent.com/58385866/87966535-0c7bd980-cac6-11ea-83e0-07c872078144.png)
3.75 cupola, all places.
![image](https://user-images.githubusercontent.com/58385866/87966652-3d5c0e80-cac6-11ea-9303-6e577511aaa1.png)
EDIT: Also broken 3.75 core places 1-3.
![image](https://user-images.githubusercontent.com/58385866/87967642-cb84c480-cac7-11ea-8679-e57a59406144.png)

**Comment by ChrisAdderley** [comment]
I'm not really that bothered, might get to it sometime in 2021.

**Comment by ChrisAdderley** [comment]
Fixed in 2-0-0 dev
