### ISSUE TITLE
Part request: Away-style centrifuge

### ISSUE THREAD

**Issue by IvanSanchez** [post-kerbin-mining-corporation/StationPartsExpansionRedux#246]
I'm aware that a new complex part is a big undertaking, and there's a real chance that this is gonna be closed with a "too much work, won't do" comment because you don't owe me anything. So, apologies in advance. (On the other hand, and unlike the Near-Future parts packs, SSPXr doesn't have a "don't ask for parts" FAQ)

I recently stumbled upon the ["Away" TV series](https://en.wikipedia.org/wiki/Away_(TV_series)), which sports a centrifuge style I hadn't seen before. Couple of screencaps from [a trailer](https://www.imdb.com/video/vi1532214809):

![imagen](https://user-images.githubusercontent.com/1125786/101741088-ed5c0380-3ac9-11eb-9007-33468eda8357.png)

![imagen](https://user-images.githubusercontent.com/1125786/101741304-31e79f00-3aca-11eb-8f8e-25c58e985ded.png)

I guess that could be a 3.75m part with two 1.25m-ish pods. I believe pods rotate 90° (similar to the Mercury-style 14-kerbal centrifuge) during deployment.

After a cursory search, I haven't been able to locate any schematics or blueprints of the spacecraft.

**Comment by ChrisAdderley** [comment]
Yeah... sorry :P. Big ol' ton of work.

**Comment by IvanSanchez** [comment]
I do understand :-)
