### ISSUE TITLE
Feature request: integration with Dynamic Battery Storage

### ISSUE THREAD

**Issue by J4SJA** [post-kerbin-mining-corporation/StationPartsExpansionRedux#248]
It seems like the mods' parts (such as the greenhouse) are not counted as consumer in the Dynamic Battery Storage overview. Would be cool and useful if added.

**Comment by ChrisAdderley** [comment]
Missed this. These parts don't produce or consume any resources, that would be the domain of whatever mod is adding that as a feature.
