### ISSUE TITLE
PMA Narrow Adapter - Incorrect node position.

### ISSUE THREAD

**Issue by omega482** [post-kerbin-mining-corporation/StationPartsExpansionRedux#252]
2-0-0 Branch
Issue description: Node position incorrect on the top side of the adapter.
Image: 
![image](https://user-images.githubusercontent.com/44052637/116588447-7c4fa800-a913-11eb-9bb1-b32e6f201c34.png)

Keep up the good work Nert, new parts look fantastic.

**Comment by ChrisAdderley** [comment]
Resolved in latest commit!
