### ISSUE TITLE
PXL-10 "harbour" Station Control Centre - Bulkhead mesh issue.

### ISSUE THREAD

**Issue by omega482** [post-kerbin-mining-corporation/StationPartsExpansionRedux#255]
Branch: 2-0-0
Part: PXL-10 "harbour" Station Control Centre
Issue: Bulkhead mesh appears to be flipped.

![image](https://user-images.githubusercontent.com/44052637/118358981-1b61da00-b579-11eb-9539-08fefd098365.png)

**Comment by ChrisAdderley** [comment]
Fixed in last commit.
