### ISSUE TITLE
PAS-T 'Oculus' Remote Telescope Requires Manned Status

### ISSUE THREAD

**Issue by xethier** [post-kerbin-mining-corporation/StationPartsExpansionRedux#284]
When using this part the orange warning message will appear stating : 

Telescope Observation requires the PAS-T 'Oculus' Remote Telescope to be manned.

The issue is providing that state. You cannot move a kerbal to the module itself and just having a manned craft does not appear to be sufficient.

At the moment this module's requirements cannot be met. (if I'm mistaken, please tell me why)

This issue did not appear until the most recent update. New or old craft using this module will exhibit this behavior.

**Comment by ChrisAdderley** [comment]
*shrug* I make mistakes sometimes. Fixed in 2.0.5
