### ISSUE TITLE
SDV-6 'Delphi' lab has inoperable EVA airlock

### ISSUE THREAD

**Issue by IvanSanchez** [post-kerbin-mining-corporation/StationPartsExpansionRedux#286]
The 5m lab (AKA "SDV-6 'Delphi'") has an EVA airlock hatch visible on the mesh, but it's not possible to use it: it's not clickable as other hatches are, and trying to send a sciencist on EVA gives the "EVA unavailable" error typical of hatch-less crewed parts.

This is using SSPXr 2.0.5 on KSP 1.11.2 .

**Comment by ChrisAdderley** [comment]
Fixed in 2.0.6.
