### ISSUE TITLE
sspx-science-1875-1 appears to transmit science but no science transmitted at end of transmission

### ISSUE THREAD

**Issue by mgalyean** [post-kerbin-mining-corporation/StationPartsExpansionRedux#288]
I imagine this is related to combination of KSP/Unity and mods, but this particular part is the one throwing errors.
I click the "Transmit Science" button in the PAW and errors below repeat during transmit and continute after screen HUD message states 100% transmitted as if something in background is still trying to get things done but no overt failure message in-game appears.  PAW still shows science in lab as full at 400 science even after "100% transmitted" HUD msg.  "Transmit Science" button remains available in PAW, clicking again results in same situation.  

Stockalike Station Parts Expansion Redux 2.0.5
KSP 1.11.2
Linux 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux
Mono JIT compiler version 6.12.0.107 (tarball Thu Dec 10 05:28:17 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

KSP.log gets lots of repeating EXC and ERRs like these (logs attached)

```
[ERR 05:18:07.490] Exception handling event onPartActionUICreate in class ModuleScienceLab:System.NullReferenceException: Object reference not set to an instance of an object
  at ModuleScienceLab.updateModuleUI () [0x00000] in <dc0e5f458c0f4571ad839b9c4153f347>:0 
  at ModuleScienceLab.onPartActionUI (Part p) [0x00025] in <dc0e5f458c0f4571ad839b9c4153f347>:0 
  at EventData`1[T].Fire (T data) [0x000b0] in <dc0e5f458c0f4571ad839b9c4153f347>:0 
[EXC 05:18:07.807] NullReferenceException: Object reference not set to an instance of an object
        ModuleScienceLab.updateModuleUI () (at <dc0e5f458c0f4571ad839b9c4153f347>:0)
        ModuleScienceLab.onPartActionUI (Part p) (at <dc0e5f458c0f4571ad839b9c4153f347>:0)
        EventData`1[T].Fire (T data) (at <dc0e5f458c0f4571ad839b9c4153f347>:0)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.Debug:LogException(Exception)
        EventData`1:Fire(Part)
        UIPartActionWindow:CreatePartList(Boolean)
        UIPartActionWindow:UpdateWindow()
        UIPartActionController:UpdateActiveWindows()
        UIPartActionController:UpdateFlight()
        UIPartActionController:Update()
...
```
LOGS:
[KSP.log](https://github.com/post-kerbin-mining-corporation/StationPartsExpansionRedux/files/7503859/KSP.log)
[Player.log](https://github.com/post-kerbin-mining-corporation/StationPartsExpansionRedux/files/7503936/Player.log)

**Comment by ChrisAdderley** [comment]
Track by some users to TAC-LS.

**Comment by 356734** [comment]
Buen post. Obtenemos la misma emoción mientras jugamos una máquina tragamonedas en línea o cualquier otro juego de azar que ofrecen los casinos en línea cuando suena la música. De hecho, los impactos del jugador pueden ser tan fuertes que pueden influir en su decisión de presionar las palancas de las máquinas una vez más o elegir un curso de acción diferente. Visita este blog para leer más sobre [La importancia de la música de casino online | El Regionalista]([https://regionalista.cl/la importancia de la musica de casino online/](https://regionalista.cl/la-importancia-de-la-musica-de-casino-online/)) Debido a lo vital que es la música para los juegos de casino, los casinos en línea crean cada vez más sus propias bandas sonoras para ayudar a los jugadores a acostumbrarse a sus experiencias.

**Comment by ChrisAdderley** [comment]
Closed, TACLS issue
