### ISSUE TITLE
Life support patches missing for sspx-cupola-greenhouse-125-1 (PAS-G 'G4RD3N' Hydroponics Cupola)

### ISSUE THREAD

**Issue by LEGIONBOSS** [post-kerbin-mining-corporation/StationPartsExpansionRedux#289]
The 1.25m greenhouse cupola is missing its life support functions.

**Comment by ChrisAdderley** [comment]
This isn't enough information to go on, and I don't maintain the LS patches themselves. Suggest you post in the forums and people will help you.
