### ISSUE TITLE
Doughnut centrifuge tube misaligned

### ISSUE THREAD

**Issue by Kopernicus-Shadows2** [post-kerbin-mining-corporation/StationPartsExpansionRedux#292]
The crew tube on the doughnut centrifuge is either too low or too short, resulting in the end not reaching the ring.
![20211126114636_1](https://user-images.githubusercontent.com/93224219/143611761-e7a16df3-657d-4e15-b156-163207b2c52a.jpg)

**Comment by ChrisAdderley** [comment]
Fixed in 2.0.7.
