### ISSUE TITLE
sspx-greenhouse-5 not in tech tree

### ISSUE THREAD

**Issue by histalonia** [post-kerbin-mining-corporation/StationPartsExpansionRedux#296]
In the file:  StationPartsExpansionRedu\Parts\Rigid\station-5\sspx-greenhouse-5-1.cfg

Line 41:
	TechRequired = experimentalScienceTech

Should be:
	TechRequired = experimentalScience

**Comment by histalonia** [comment]
This is without a tech tree mod.

**Comment by ChrisAdderley** [comment]
Fixed in 2.0.6
