### ISSUE TITLE
Support for Kerbalism

### ISSUE THREAD

**Issue by NightShift10125** [post-kerbin-mining-corporation/StationPartsExpansionRedux#297]
I would like to add a request for Kerbalism support to be added to StationPartsExpansionRedux.
The many labs added by your mod are not configured, I can tell based on the missing "Configure Laboratory Experiments" tab.
Along side the labs the ' PAS-T 'Oculus' Remote Telescope ' needs to be configured to gather science over a long period of time instead of all at once.
Last but not least the green house will need some love as well, the 'PXL-R4NCH-3R Hydroponics Module' and 'PPD-F412M Hydroponics Module' work but both yield less food than the 'GreenHouse' from Kerbalism.

With all that said and done would it kill you to explain how you configured everything?
I got some other mods with labs and greenhouses I'd like to get running.

(Don't mind the 'Blacksmith Level' on the science lab, thats part of another mod I'm testing)

![Screenshot 2022-03-08 150626](https://user-images.githubusercontent.com/42304378/157333785-c9e3c0bd-675d-415f-8421-20c464477edf.png)
![Screenshot 2022-03-08 150633](https://user-images.githubusercontent.com/42304378/157333792-8a4c4988-1771-4168-b054-d276dc6ee5fe.png)
![Screenshot 2022-03-08 150715](https://user-images.githubusercontent.com/42304378/157333857-e69d0794-5718-4a2e-9c12-c3a79b50661f.png)

**Comment by ChrisAdderley** [comment]
Kerbalism support is up to Kerbalism, not this mod. Ask them.
