### ISSUE TITLE
Dark station interiors 

### ISSUE THREAD

**Issue by Mattro843** [post-kerbin-mining-corporation/StationPartsExpansionRedux#298]
Wean booting up KSP and make a space station around Dipic I got Dark station Interiors.

**Comment by Mattro843** [comment]
https://cdn.discordapp.com/attachments/939302543354364004/952103895436517436/20220311231840_1.jpg

**Comment by ChrisAdderley** [comment]
Not a bug, you haven't installed the interiors so you don't get interiors.
