### ISSUE TITLE
PMA-AR Radial Attachment Module has incomplete description.

### ISSUE THREAD

**Issue by Vaskritaya** [post-kerbin-mining-corporation/StationPartsExpansionRedux#300]
The part's description cuts off abruptly and is incomplete, at least in English. Specifically, in en-us.cfg, the relevant line, 262, reads
>    #LOC_SSPX_sspx-attach-1875-1_description = Used to connect PMA modules radially to

**Comment by ChrisAdderley** [comment]
Fixed in 2.0.7
