### ISSUE TITLE
Observe Local Space has missing string

### ISSUE THREAD

**Issue by Vaskritaya** [post-kerbin-mining-corporation/StationPartsExpansionRedux#301]
Doing space observation with the Oculus or Delphi while grounded on many places in Kerbin results in a missing string. From my testing, the experiment reports properly from low Kerbin orbit and in the generic "KSC" biome, but the string is missing when observing from the campus-specific mini-biomes, shores, and grassland, as some examples I found.

Attached are some examples of both successful and failed experiments in various Kerbin locales.

![20220406050545_1](https://user-images.githubusercontent.com/22992007/161943646-0f050d7f-3dc6-4378-ad65-3e74322eaf4a.jpg)
![20220406051518_1](https://user-images.githubusercontent.com/22992007/161943651-78ee31c9-c954-4cf9-bdb0-4c3f6fd27adc.jpg)
![20220406051535_1](https://user-images.githubusercontent.com/22992007/161943655-0cc85162-f3b4-4462-8b64-78fdd114d84a.jpg)

**Comment by ChrisAdderley** [comment]
Should be resolve in 2.0.7.
