### ISSUE TITLE
Gaps between mount rings and hull on some parts

### ISSUE THREAD

**Issue by Rodg88** [post-kerbin-mining-corporation/StationPartsExpansionRedux#302]
There's a small gap between the mount rings and the main hull of the titan hab, as seen here:
![image](https://user-images.githubusercontent.com/2611674/162722713-99555d3b-dd9a-4ffb-bd77-75d6df47b3dd.png)

Also on the large domes:
![image](https://user-images.githubusercontent.com/2611674/162723258-35b5933b-05fe-4072-8409-ab02b43cf9be.png)

And on the Atlas hab, there's a gap at the top, and some z-fighting overlap on the bottom:
![image](https://user-images.githubusercontent.com/2611674/162723376-dd51aec7-2e00-49c8-9b7e-85c1694a56b6.png)
It doesn't really show the z-fighting, but this is the location of it.
![image](https://user-images.githubusercontent.com/2611674/162723432-c33aafa4-8540-4e6b-a7d4-f3a8e601e6af.png)

And on the Minerva command module:
![image](https://user-images.githubusercontent.com/2611674/162723917-91bf7877-69bb-49d6-aaf3-25a9bd944266.png)

The big lab also has a seam gap on one side 
![image](https://user-images.githubusercontent.com/2611674/162741307-96eda194-d155-4597-ba2d-bdae4bab77e3.png)

**Comment by ChrisAdderley** [comment]
Fixed what I will in 2.0.7
