### ISSUE TITLE
SDV-G4 observation dome extra or misplaced collider

### ISSUE THREAD

**Issue by Rodg88** [post-kerbin-mining-corporation/StationPartsExpansionRedux#303]
The hologram dome seems to have an extra collider about 9m above it. ![image](https://user-images.githubusercontent.com/2611674/162740807-8d178355-b934-4214-a71e-038c20a02d03.png)

The .mu is also missing the animation for the hologram/projector deployment

**Comment by ChrisAdderley** [comment]
Fixed in 2.0.7
