### ISSUE TITLE
Sections of station parts emit like windows

### ISSUE THREAD

**Issue by willfulZephyr** [post-kerbin-mining-corporation/StationPartsExpansionRedux#310]
After applying 2.0.8, some sections of several station parts began acting like "windows", emitting light when the part had the lights turned on, and returning to the normal texture when the lights are turned off
![screenshot10](https://user-images.githubusercontent.com/96021116/173252131-a4066f9a-aca8-4eae-ba3a-9f251c4c7f80.png)
.
I can add a mod list if needed.

**Comment by willfulZephyr** [comment]
At least I think these are SSPX station parts, it started with that update. Please send me packing if they aren't.

**Comment by ChrisAdderley** [comment]
I don't know how I did this but it should be fixed now.
